Vagrant.configure('2') do |config|
  config.vm.box = 'debian/jessie64'
  config.vm.synced_folder '..', '/vagrant'
  config.vm.network 'forwarded_port', guest: 3000, host: 3000
  config.vm.provision 'shell', path: 'provision.sh'
end
