default: &default
  adapter: postgresql
  port: 5432
  schema_search_path: 'public'

development:
  <<: *default
  host: localhost
  database: loadtest
  username: postgres
  password: <%= ENV['RAILS_DB_PWD'] || 'password' %>

test: &test
  <<: *default
  host: <%= ENV['CI'] ? YAML.load_file(File.join(Rails.root, 'config', 'ci_config.yml'))['test_host'] : 'localhost' %>
  database: loadtest_test
  username: postgres
  password: <%= ENV['RAILS_DB_PWD'] || 'password' %>

production:
  <<: *default
  host: localhost
  database: loadtest
  username: postgres
  password: <%= ENV['RAILS_DB_PWD'] %>