# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f2f25006779a69f89c62420080452b8f6d48aa5168414ab9a59e6539742680d52ed1cbf0151cd6aeceb9a0b1a1edf79db0e9ba96e648dcca0c78aa921eaaac5

test:
  secret_key_base: 584362b50388d38c2c41c20a85cdba24ea78f4c489456a2093dabb41bc1ca4bec5e298dfca3390d8f99dc117b08f8c3fce79474a2b143a0f1a79cf466a3c7348

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>